name: Deploy to Hetzner VPS

on: push

concurrency: { group: deploy-scrum-poker-planning, cancel-in-progress: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload project files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{ secrets.VPS_USER }}/apps/scrum-poker-planning"
          overwrite: true
          strip_components: 0
          exclude: ".git,node_modules,.next,.DS_Store"

      - name: Write .env with Convex URL
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.VPS_USER }}/apps/scrum-poker-planning
            echo "NEXT_PUBLIC_CONVEX_URL=${{ secrets.CONVEX_URL }}" > .env
            chmod 600 .env

      - name: Build and start with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/${{ secrets.VPS_USER }}/apps/scrum-poker-planning
            docker compose build --pull
            docker compose up -d
            docker image prune -f || true
